name: CI
on: push
env:
  CABAL_DIR: ${{ github.workspace }}/.cabal
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with:
        key: nix-${{ hashFiles('shell.nix') }}
        nix_file: 'shell.nix'
    - uses: cachix/cachix-action@v8
      with:
        name: codygman5
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "echo OK"
    - run: nix-shell --pure --run "bazel build ..."
