name: CI
on: push
env:
  CABAL_DIR: ${{ github.workspace }}/.cabal
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with:
        key: nix-${{ hashFiles('buildshell.nix') }}
        nix_file: 'buildshell.nix'
    - run: ls /nix/store
    - run: nix-shell --run "echo OK"
    - run: nix-shell --pure --run "bazel build ..."
