name: CI
on: push
env:
  CABAL_DIR: ${{ github.workspace }}/.cabal
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        ghc: [ 8.10.2 ]
        cabal: [ 3.2.0.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal freeze --verbose=3
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cabal
            dist-newstyle
            ghc-cache
          key: b-${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            b-${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
            b-${{ matrix.os }}-${{ matrix.ghc }}-
      - run: mkdir -p ghc-cache
      - run: for f in $( find ghc-cache -name '*.hi' ); do echo $f; ghc --show-iface $f; done
      - run: cabal build --ghc-options=-v --verbose=3
      - run: cabal exec -- ghc --make Ichor -hidir ghc-cache -odir ghc-cache
      - run: for f in $( find ghc-cache -name '*.hi' ); do echo $f; ghc --show-iface $f; done
