name: CI
on: push
env:
  CABAL_DIR: ${{ github.workspace }}/.cabal
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        ghc: [ 8.10.2 ]
        cabal: [ 3.2.0.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal freeze --verbose=3
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cabal
            dist-newstyle
          key: d-${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            d-${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
            d-${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal build
